name: moeda_brasil
description: Biblioteca para formatação de valores monetários no padrão brasileiro (BRL/Real).
version: 1.1.0
repository: https://github.com/victorprsilva/moeda-brasil
homepage: https://github.com/victorprsilva/moeda-brasil

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
